### ISSUE TITLE
Great resource!

### ISSUE THREAD

**Issue by robertritz** [tugstugi/mongolian-nlp#1]
Thanks for posting these amazing resources! These are a really great place to get started. In the next year I am really interested in getting sentiment analysis and NER working in Mongolian. Is the biggest problem labeled datasets currently?

**Comment by tugstugi** [comment]
yes, the biggest problem is the lack of open datasets.

For NER, I have started to label myself some data but stopped because I am currently busy. If you want to contribute to label a NER dataset, you can find more info here: https://github.com/tugstugi/mongolian-nlp/tree/master/NER

**Comment by tugstugi** [comment]
@robertritz I have released a Mongolian NER dataset containing 10K sentences with 4 categories `LOCATION`, `PERSON`, `ORGANIZATION` and `MISC`: https://github.com/tugstugi/mongolian-nlp/blob/master/datasets/NER_v1.0.json.gz

In the near future, we are also going to release a Google BERT based NER.
