### ISSUE TITLE
How to use Python to display traditional Mongolian? Some Mongolian fonts are not connected, but they can be connected in TXT or Word..

### ISSUE THREAD

**Issue by dlml** [tugstugi/mongolian-nlp#10]

**Comment by tugstugi** [comment]
You should use probably Harfbuzz or similar libraries to shape correctly the traditional mongolian text.

**Comment by dlml** [comment]
Thank you for your reply. Yes, I haven't found it yet. Arabic series can be passed through Arabic_ Reshape tries to shape the text correctly, but I want to achieve it in the same way. I find that the same Mongolian character has multiple codes in the middle.

**Comment by tugstugi** [comment]
You can also use pango-view and write the result into an image file and read back with python.
Sample code for pango view:
```
pango-view --output=out.png --rotate=-90 --no-display --font='Noto Sans Mongolian 12' --margin='5 0 5 0' --text "ᠮᠣᠩᠭᠣᠯ"
```
