### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by cidrugHug8** [tugstugi/mongolian-nlp#3]
Hi thereh,

The dataset (Mongolian POS dataset of the Mongolian National University) cannot be downloaded from the following link.
http://www.panl10n.net/center-for-research-on-language-processing-crlp-national-university-of-mongolia-mongolia/

Can you give me a link where I can download the dataset?

Thank you.

**Comment by tugstugi** [comment]
You can use archiv.org. Here is the link https://web.archive.org/web/20150105023831/http://www.panl10n.net/english/Outputs%20Phase%202/CCs/Mongolia/NUM/Software/2009/TaggedCorpus.rar

**Comment by cidrugHug8** [comment]
Thank you very much. It was helpful.
