### ISSUE TITLE
Add Coqui Mongolian STT model

### ISSUE THREAD

**Issue by JRMeyer** [tugstugi/mongolian-nlp#4]
Hi @tugstugi :wave: 

Firstly, thanks for contributing so much to open speech tech for Mongolian!

You might add a link to the Mongolian model in the Coqui Model Zoo <https://coqui.ai/mongolian/itml/v0.1.1>

The model zoo is constantly growing, and if you'd like to train any Mongolian STT or TTS models, we'd love to put them in the zoo!

Feel free to chat with us in our chat room :) <https://gitter.im/coqui-ai/STT>

**Comment by tugstugi** [comment]
Added the link: https://github.com/tugstugi/mongolian-nlp/commit/3a48a8dd1d00ec9d2b46ae367748142b7a7cc2f1
