### ISSUE TITLE
Mongolian Morphology

### ISSUE THREAD

**Issue by kbatsuren** [tugstugi/mongolian-nlp#7]
Dear @tugstugi,

Recently, I have released multiple morphological resources. It would be so nice if you link them from here. :)
I believe they are useful for the community. Here are the links. 

- Inflectional morphology - https://github.com/unimorph/khk
- Derivational morphology - https://github.com/kbatsuren/MorphyNet

Best regards,
Huygaa

**Comment by tugstugi** [comment]
@kbatsuren thanks make a pull request. I will merge it.

Greetings
Tuguldur

**Comment by kbatsuren** [comment]
Okay, I sent the pull request here. https://github.com/tugstugi/mongolian-nlp/pull/8

Thanks. :)

**Comment by tugstugi** [comment]
merged.
